[project]
name = "my-mlops-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.14.0",
    "docker>=7.1.0",
    "evidently>=0.7.21",
    "great-expectations>=1.16.1",
    "hopsworks>=4.8.1",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.6",
    "kedro-mlflow>=2.0.2",
    "mlflow>=3.11.1",
    "optuna>=4.8.0",
    "prefect>=3.6.27",
    "setuptools<81",
    "streamlit>=1.52.0",
    "ucimlrepo>=0.0.7",
    "vadersentiment>=3.3.2",
    "ydata-profiling<=4.18.3",
]

[tool.kedro]
package_name = "sp500_mlops_pipeline"
project_name = "sp500-mlops-pipeline"
source_dir = "src"
kedro_init_version = "1.4.0"

[tool.kedro_telemetry]
project_id = "2ba70423afac439da485645258742d0a"
