"""Nodes for the optional Hopsworks offline feature-store integration."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import pandas as pd
from dotenv import load_dotenv

from sp500_mlops_pipeline.pipelines.data_feat_engineering.nodes import (
    MARKET_FEATURE_COLUMNS,
    TARGET_COLUMN,
)


DATE_COLUMN = "Date"
FEATURE_GROUP_DESCRIPTION = (
    "S&P 500 market features generated by the Kedro feature-engineering pipeline. "
    "The target is stored only for reproducible offline supervised training."
)
FEATURE_VIEW_DESCRIPTION = (
    "Offline training view exposing canonical S&P 500 model features and target."
)


def upload_sp500_features_to_hopsworks(
    feature_data: pd.DataFrame,
    feature_group_name: str,
    feature_group_version: int,
    feature_view_name: str,
    feature_view_version: int,
    env_path: str = ".env",
    wait_for_job: bool = True,
) -> dict[str, Any]:
    """Upload local feature data to Hopsworks and create an offline training view."""
    validated_data = validate_feature_store_dataframe(feature_data)
    project = connect_to_hopsworks(env_path=env_path)
    feature_store = project.get_feature_store()
    feature_group = create_or_get_sp500_feature_group(
        feature_store=feature_store,
        feature_group_name=feature_group_name,
        feature_group_version=feature_group_version,
    )
    insert_sp500_feature_data(
        feature_group=feature_group,
        feature_data=validated_data,
        wait_for_job=wait_for_job,
    )
    feature_view = create_or_get_sp500_feature_view(
        feature_store=feature_store,
        feature_group=feature_group,
        feature_view_name=feature_view_name,
        feature_view_version=feature_view_version,
    )

    return {
        "feature_group_name": feature_group_name,
        "feature_group_version": feature_group_version,
        "feature_view_name": feature_view_name,
        "feature_view_version": feature_view_version,
        "primary_key": DATE_COLUMN,
        "event_time": DATE_COLUMN,
        "feature_columns": MARKET_FEATURE_COLUMNS,
        "target_column": TARGET_COLUMN,
        "rows_uploaded": int(len(validated_data)),
        "feature_view_created": feature_view is not None,
    }


def validate_feature_store_dataframe(feature_data: pd.DataFrame) -> pd.DataFrame:
    """Validate and prepare the canonical offline feature-store dataframe."""
    if feature_data.empty:
        raise ValueError("Feature-store upload received an empty feature dataset.")

    required_columns = [DATE_COLUMN, *MARKET_FEATURE_COLUMNS, TARGET_COLUMN]
    missing_columns = [
        column for column in required_columns if column not in feature_data.columns
    ]
    if missing_columns:
        raise ValueError(
            "Feature-store upload is missing required canonical columns: "
            f"{missing_columns}"
        )

    upload_data = feature_data.loc[:, required_columns].copy()
    upload_data[DATE_COLUMN] = pd.to_datetime(
        upload_data[DATE_COLUMN],
        errors="raise",
    )
    upload_data = upload_data.sort_values(DATE_COLUMN).reset_index(drop=True)

    if upload_data[DATE_COLUMN].duplicated().any():
        duplicate_dates = upload_data.loc[
            upload_data[DATE_COLUMN].duplicated(),
            DATE_COLUMN,
        ].dt.strftime("%Y-%m-%d")
        raise ValueError(
            "Feature-store upload requires unique Date values. "
            f"Duplicate examples: {duplicate_dates.head(5).tolist()}"
        )

    if TARGET_COLUMN in MARKET_FEATURE_COLUMNS:
        raise ValueError(
            f"Target column {TARGET_COLUMN!r} must not be part of model features."
        )

    invalid_target_values = set(upload_data[TARGET_COLUMN].dropna().unique()) - {0, 1}
    if invalid_target_values:
        raise ValueError(
            f"{TARGET_COLUMN} must contain only 0 or 1 for offline training. "
            f"Found: {sorted(invalid_target_values)}"
        )

    return upload_data


def connect_to_hopsworks(env_path: str = ".env"):
    """Connect to Hopsworks using local environment variables without logging secrets."""
    load_dotenv(dotenv_path=Path(env_path), override=False)
    api_key = os.getenv("HOPSWORKS_API_KEY")
    project_name = os.getenv("HOPSWORKS_PROJECT")
    host = _normalize_hopsworks_host(os.getenv("HOPSWORKS_HOST"))

    missing_variables = [
        variable
        for variable, value in {
            "HOPSWORKS_API_KEY": api_key,
            "HOPSWORKS_PROJECT": project_name,
            "HOPSWORKS_HOST": host,
        }.items()
        if not value
    ]
    if missing_variables:
        raise ValueError(
            "Missing required Hopsworks environment variables: "
            f"{missing_variables}. Configure them in the local .env file."
        )

    try:
        import hopsworks
    except ImportError as exc:
        raise ImportError(
            "The optional Hopsworks dependency is not installed in this environment. "
            "Install project dependencies before running the feature_store pipeline."
        ) from exc

    return hopsworks.login(
        host=host,
        project=project_name,
        api_key_value=api_key,
    )


def _normalize_hopsworks_host(host: str | None) -> str | None:
    """Return the Hopsworks hostname without URL scheme or path components."""
    if host is None:
        return None

    normalized = host.strip()
    if normalized.startswith("https://"):
        normalized = normalized.removeprefix("https://")
    elif normalized.startswith("http://"):
        normalized = normalized.removeprefix("http://")

    return normalized.strip("/")


def create_or_get_sp500_feature_group(
    feature_store,
    feature_group_name: str,
    feature_group_version: int,
):
    """Create or retrieve the offline S&P 500 market-feature group."""
    return feature_store.get_or_create_feature_group(
        name=feature_group_name,
        version=feature_group_version,
        primary_key=[DATE_COLUMN],
        event_time=DATE_COLUMN,
        time_travel_format="HUDI",
        hudi_precombine_key=DATE_COLUMN,
        online_enabled=False,
        description=FEATURE_GROUP_DESCRIPTION,
    )


def insert_sp500_feature_data(
    feature_group,
    feature_data: pd.DataFrame,
    wait_for_job: bool = True,
) -> None:
    """Insert the validated local feature dataset into the Feature Group."""
    feature_group.insert(
        feature_data,
        write_options={"wait_for_job": wait_for_job},
    )


def create_or_get_sp500_feature_view(
    feature_store,
    feature_group,
    feature_view_name: str,
    feature_view_version: int,
):
    """Create or retrieve the offline training Feature View.

    The Feature View exposes canonical model features plus the target for offline
    training. The target remains explicitly excluded from ``MARKET_FEATURE_COLUMNS``.
    """
    selected_columns = [*MARKET_FEATURE_COLUMNS, TARGET_COLUMN]
    query = feature_group.select(selected_columns)
    return feature_store.get_or_create_feature_view(
        name=feature_view_name,
        version=feature_view_version,
        query=query,
        labels=[TARGET_COLUMN],
        description=FEATURE_VIEW_DESCRIPTION,
    )
